//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DirecAct.Droid.ServiceDirectorio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DirectorioSoap", Namespace="http://tempuri.org/")]
    public partial class Directorio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AccesoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DatosAreasOperationCompleted;
        
        private System.Threading.SendOrPostCallback DatosFuncionariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback DatosFuncAreaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DatosBusqAreasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaNotificacionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertaNotificacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Directorio() {
            this.Url = "http://132.248.80.146/ws/directorio.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AccesoCompletedEventHandler AccesoCompleted;
        
        /// <remarks/>
        public event DatosAreasCompletedEventHandler DatosAreasCompleted;
        
        /// <remarks/>
        public event DatosFuncionariosCompletedEventHandler DatosFuncionariosCompleted;
        
        /// <remarks/>
        public event DatosFuncAreaCompletedEventHandler DatosFuncAreaCompleted;
        
        /// <remarks/>
        public event DatosBusqAreasCompletedEventHandler DatosBusqAreasCompleted;
        
        /// <remarks/>
        public event ConsultaNotificacionesCompletedEventHandler ConsultaNotificacionesCompleted;
        
        /// <remarks/>
        public event InsertaNotificacionCompletedEventHandler InsertaNotificacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Acceso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Acceso(string strUsuario, string strPass) {
            object[] results = this.Invoke("Acceso", new object[] {
                        strUsuario,
                        strPass});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AccesoAsync(string strUsuario, string strPass) {
            this.AccesoAsync(strUsuario, strPass, null);
        }
        
        /// <remarks/>
        public void AccesoAsync(string strUsuario, string strPass, object userState) {
            if ((this.AccesoOperationCompleted == null)) {
                this.AccesoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccesoOperationCompleted);
            }
            this.InvokeAsync("Acceso", new object[] {
                        strUsuario,
                        strPass}, this.AccesoOperationCompleted, userState);
        }
        
        private void OnAccesoOperationCompleted(object arg) {
            if ((this.AccesoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccesoCompleted(this, new AccesoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DatosAreas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DatosAreas() {
            object[] results = this.Invoke("DatosAreas", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DatosAreasAsync() {
            this.DatosAreasAsync(null);
        }
        
        /// <remarks/>
        public void DatosAreasAsync(object userState) {
            if ((this.DatosAreasOperationCompleted == null)) {
                this.DatosAreasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDatosAreasOperationCompleted);
            }
            this.InvokeAsync("DatosAreas", new object[0], this.DatosAreasOperationCompleted, userState);
        }
        
        private void OnDatosAreasOperationCompleted(object arg) {
            if ((this.DatosAreasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DatosAreasCompleted(this, new DatosAreasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DatosFuncionarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DatosFuncionarios() {
            object[] results = this.Invoke("DatosFuncionarios", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DatosFuncionariosAsync() {
            this.DatosFuncionariosAsync(null);
        }
        
        /// <remarks/>
        public void DatosFuncionariosAsync(object userState) {
            if ((this.DatosFuncionariosOperationCompleted == null)) {
                this.DatosFuncionariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDatosFuncionariosOperationCompleted);
            }
            this.InvokeAsync("DatosFuncionarios", new object[0], this.DatosFuncionariosOperationCompleted, userState);
        }
        
        private void OnDatosFuncionariosOperationCompleted(object arg) {
            if ((this.DatosFuncionariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DatosFuncionariosCompleted(this, new DatosFuncionariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DatosFuncArea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DatosFuncArea(int idArea) {
            object[] results = this.Invoke("DatosFuncArea", new object[] {
                        idArea});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DatosFuncAreaAsync(int idArea) {
            this.DatosFuncAreaAsync(idArea, null);
        }
        
        /// <remarks/>
        public void DatosFuncAreaAsync(int idArea, object userState) {
            if ((this.DatosFuncAreaOperationCompleted == null)) {
                this.DatosFuncAreaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDatosFuncAreaOperationCompleted);
            }
            this.InvokeAsync("DatosFuncArea", new object[] {
                        idArea}, this.DatosFuncAreaOperationCompleted, userState);
        }
        
        private void OnDatosFuncAreaOperationCompleted(object arg) {
            if ((this.DatosFuncAreaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DatosFuncAreaCompleted(this, new DatosFuncAreaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DatosBusqAreas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DatosBusqAreas(string strArea) {
            object[] results = this.Invoke("DatosBusqAreas", new object[] {
                        strArea});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DatosBusqAreasAsync(string strArea) {
            this.DatosBusqAreasAsync(strArea, null);
        }
        
        /// <remarks/>
        public void DatosBusqAreasAsync(string strArea, object userState) {
            if ((this.DatosBusqAreasOperationCompleted == null)) {
                this.DatosBusqAreasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDatosBusqAreasOperationCompleted);
            }
            this.InvokeAsync("DatosBusqAreas", new object[] {
                        strArea}, this.DatosBusqAreasOperationCompleted, userState);
        }
        
        private void OnDatosBusqAreasOperationCompleted(object arg) {
            if ((this.DatosBusqAreasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DatosBusqAreasCompleted(this, new DatosBusqAreasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaNotificaciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaNotificaciones() {
            object[] results = this.Invoke("ConsultaNotificaciones", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaNotificacionesAsync() {
            this.ConsultaNotificacionesAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaNotificacionesAsync(object userState) {
            if ((this.ConsultaNotificacionesOperationCompleted == null)) {
                this.ConsultaNotificacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaNotificacionesOperationCompleted);
            }
            this.InvokeAsync("ConsultaNotificaciones", new object[0], this.ConsultaNotificacionesOperationCompleted, userState);
        }
        
        private void OnConsultaNotificacionesOperationCompleted(object arg) {
            if ((this.ConsultaNotificacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaNotificacionesCompleted(this, new ConsultaNotificacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertaNotificacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertaNotificacion(string strTexto, string strSender, string strReceiver) {
            object[] results = this.Invoke("InsertaNotificacion", new object[] {
                        strTexto,
                        strSender,
                        strReceiver});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertaNotificacionAsync(string strTexto, string strSender, string strReceiver) {
            this.InsertaNotificacionAsync(strTexto, strSender, strReceiver, null);
        }
        
        /// <remarks/>
        public void InsertaNotificacionAsync(string strTexto, string strSender, string strReceiver, object userState) {
            if ((this.InsertaNotificacionOperationCompleted == null)) {
                this.InsertaNotificacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaNotificacionOperationCompleted);
            }
            this.InvokeAsync("InsertaNotificacion", new object[] {
                        strTexto,
                        strSender,
                        strReceiver}, this.InsertaNotificacionOperationCompleted, userState);
        }
        
        private void OnInsertaNotificacionOperationCompleted(object arg) {
            if ((this.InsertaNotificacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaNotificacionCompleted(this, new InsertaNotificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AccesoCompletedEventHandler(object sender, AccesoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccesoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccesoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DatosAreasCompletedEventHandler(object sender, DatosAreasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatosAreasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DatosAreasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DatosFuncionariosCompletedEventHandler(object sender, DatosFuncionariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatosFuncionariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DatosFuncionariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DatosFuncAreaCompletedEventHandler(object sender, DatosFuncAreaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatosFuncAreaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DatosFuncAreaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DatosBusqAreasCompletedEventHandler(object sender, DatosBusqAreasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatosBusqAreasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DatosBusqAreasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ConsultaNotificacionesCompletedEventHandler(object sender, ConsultaNotificacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaNotificacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaNotificacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void InsertaNotificacionCompletedEventHandler(object sender, InsertaNotificacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaNotificacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaNotificacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591